# Generated by Django 4.0.3 on 2022-03-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_scholarship_category_scholarship_by_goi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='by_GOI',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='category',
            field=models.ManyToManyField(to='core.category'),
        ),
    ]
