# Generated by Django 4.0.3 on 2022-03-07 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_remove_scholarship_by_goi_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='category',
            new_name='Type',
        ),
    ]
