# Generated by Django 4.0.3 on 2022-03-07 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_category_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='Type',
            new_name='type',
        ),
    ]
