# Generated by Django 4.0.6 on 2022-07-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_verified_scholarship_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='reviewed',
        ),
    ]
